-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "20")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(89b4faff)"},
                angle = 45,
            },
        },
        gaps_in = 2,
        gaps_out = 4,
        layout = "scrolling",
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.0,
    bezier = "default",
    style = "slidevert",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@120.00Hz",
    position = "0x0",
    scale = 1.5,
    cm = "srgb",
})
